//DATASET
#define _RATE_ 10
#define _WIDTH_ 1920
#define _HEIGHT_ 1080
#define _VEHICLES_ true
#define _PEDS_ true
#define _TRAFFIC_SIGNS_ false
#define _DIRECTION_ false
#define _REWARD_ false
#define _THROTTLE_ false
#define _BRAKE_ false
#define _STEERING_ false
#define _SPEED_ false
#define _YAW_RATE_ false
#define _DRIVING_MODE_ false
#define _LOCATION_ false
#define _TIME_ false
#define _OFFSCREEN_ false
#define _SHOWBOXES_ false
#define _POINTCLOUDS_ true
#define _STATIONARY_SCENE_ false
#define _COLLECT_TRACKING_ false
